### ISSUE TITLE
Local authetication

### ISSUE THREAD

**Issue by Nedvedyy** [domfarolino/angular2-login-seed#1]
Hi,

Nice job. Thanks.

Any plan to add in local authentication? 

Regards
Ned

**Comment by domfarolino** [comment]
Yes that's something I want to get to this week. Shouldn't be too difficult, however if you wish to contribute be my guest!

**Comment by domfarolino** [comment]
@Nedvedyy The feature is almost implemented. Should be up within a day, only thing is it will not consist of asynchronous validation for username and email on the registration page due to [this ng2 issue](https://github.com/angular/angular/issues/6895). Some of the pieces for that will be put in place but it won't be implemented fully. Me and @babeal went through this quite a bit this evening and the functionality of using `debounceTime` with async validators is kinda...odd right now

**Comment by domfarolino** [comment]
Commit [99516f3](https://github.com/domfarolino/angular2-login-seed/commit/99516f3ac6c0373455983d3ab1fd6232918d6275) adds feature and closes issue
