### ISSUE TITLE
Custom Express Server setup should mention the 'apiBase' variable

### ISSUE THREAD

**Issue by bdinsmor** [domfarolino/angular2-login-seed#17]
In src/app, the app.module.ts file needs to have the apiBase value point to the local express server if you wish to run locally.

Great project!!

**Comment by domfarolino** [comment]
I don't think this is the case.  The local angular app should be able to hit the remote API locally since the remote API allows cors on the localhost origin. This means anyone should be able to pull the entire project down, build the front-end and hit the remote API hosted on Heroku.

Optionally, you can follow the instructions in the README to setup your own database for your local express server however since that requires a lot more work to get up and running, I have the apiBase set to the remote API so people can get off the ground quickly. Is this not working for you?

**Comment by bdinsmor** [comment]
Running a local dev express server is working for me after changing the apiBase to hit my local express server (http://localhost:5000) - which is why I tried to label the issue as only pertaining to "Custom Express Server"

Clear as mud?  Feel free to close if you think it is a poorly worded issue - it is just impossible to have the GUI hit the local express back-end without changing that variable - that is all I wanted to point out.

**Comment by domfarolino** [comment]
Oh ok I see. Yes there could probably be better documentation around this in the README to tell people to switch that value. If you want to submit a documentation PR to clear the issue up for other people in the future that would be great.

**Comment by domfarolino** [comment]
Do you want to go ahead and change the doc or do you want me to? Personally I just like getting people involved in projects so if you want to throw something up I'd be happy to review it.

**Comment by adamhpan** [comment]
I've made a PR for this #20 . 
Check it out if it help you out @bdinsmor.

**Comment by domfarolino** [comment]
Thanks!
