### ISSUE TITLE
SQL Documentation

### ISSUE THREAD

**Issue by PhilippeCorreges** [domfarolino/angular2-login-seed#3]
Hello,

I am not sure howTo do and if it is possible but The app is configured to work with MySql.
Should be good to write it maybe.

Thanks

Philippe

**Comment by domfarolino** [comment]
Are you thinking something along the lines of supplementary documentation in the Readme on getting started?

**Comment by PhilippeCorreges** [comment]
Yes. Just for information as I cloned the repo to see at the end I did not have mySQL :(

**Comment by domfarolino** [comment]
@PhilippeCorreges New changes have been made so that to run the application locally you no longer have to build a server, database, API, etc. You simply pull the application down and run it and it accesses an online API. Documentation coming in a few days will reflect these changes and show you how to easily run the application locally with minimal hassle. `git pull` & `npm install && npm start` should be all you need.

**Comment by PhilippeCorreges** [comment]
I ll try this later as I am heavy loaded.

Nevertheless thanks for your effort!!
